=== Tso-Battleship/A2014-Battleship/A2014-Battleship-XML-DEMO/xml-test/battleship_xml.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="grille" type="grilleType">
    <xs:annotation>
      <xs:documentation> Fin du mode de jeu CLASSIQUE </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="piecesType">
    <xs:sequence>
      <xs:element type="xs:string" name="cases"/>
      <xs:element type="xs:string" name="description"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="ship" use="optional"/>
  </xs:complexType>
  <xs:complexType name="pathType">
    <xs:sequence>
      <xs:element type="piecesType" name="pieces" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="emplacement"/>
  </xs:complexType>
  <xs:complexType name="modeDeJeuType">
    <xs:sequence>
      <xs:element type="xs:string" name="taille"/>
      <xs:element type="pathType" name="path">
        <xs:annotation>
          <xs:documentation><![CDATA[<tir>
    <toucher img = "hit.png"> </toucher>
    <rater img2 = "miss.png"> </rater>
    </tir>]]></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="nomDeJeu"/>
  </xs:complexType>
  <xs:complexType name="grilleType">
    <xs:sequence>
      <xs:element type="modeDeJeuType" name="modeDeJeu"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Tso-Battleship/A2014-Battleship/BattleShip-2014/BattleShip-2014/bin/Debug/battleship_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<grille 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="D:/Windows/Documents/GitHub/A2014-Battleship/BattleShip-2014/battleship_xml.xsd">
  <modeDeJeu nomDeJeu="Classique">
	<taille>10,10</taille>
	<path emplacement="..../images/bateau">
      <pieces ship ="aircraftCarrier.png">
		<cases>0,0:0,1:0,2:0,3:0,4</cases>
		<description>aircraftCarrier</description>
	  </pieces>
	  <pieces ship ="battleShip.png">
			<cases>0,0:0,1:0,2:0,3</cases>
		<description>battleShip</description>
	  </pieces>
	  <pieces ship ="destroyer.png">
			<cases>0,0:0,1:0,2</cases>
		<description>destroyer</description>
	  </pieces>
	  <pieces ship ="destroyer.png">
		<cases>0,0:0,1:0,2</cases>
		<description>destroyer2</description>
	  </pieces>
	  <pieces ship ="patrolBoat.png">
			<cases>0,0:0,1</cases>
		<description>patrolBoat</description>
	  </pieces>
	  <!--<tir>
		<toucher img = "hit.png"> </toucher>
		<rater img2 = "miss.png"> </rater>
	  </tir>-->
	</path>
	
  </modeDeJeu>
  <!-- Fin du mode de jeu CLASSIQUE -->
 </grille>
